version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rapid
      SPRING_DATASOURCE_USERNAME: sucode
      SPRING_DATASOURCE_PASSWORD: sucode

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rapid
      POSTGRES_USER: sucode
      POSTGRES_PASSWORD: sucode
