name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 77.237.234.122 >> ~/.ssh/known_hosts

    - name: Copy docker-compose.yml to server
      run: |
        scp -o StrictHostKeyChecking=no docker-compose.yml root@77.237.234.122:/path/to/docker-compose.yml

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@77.237.234.122 "docker-compose -f /path/to/docker-compose.yml up -d"
