name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag my-app my-dockerhub-username/my-app:latest
        docker push my-dockerhub-username/my-app:latest

    - name: Deploy to Server
      run: |
        ssh root@77.237.234.122 "docker pull my-dockerhub-username/my-app:latest && docker-compose -f /path/to/docker-compose.yml up -d"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
