name: Build and Deploy Spring Boot App Java

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in repository
        run: ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: root
          VPS_HOST: 77.237.234.122
        run: |
          # Crear archivo temporal para la clave SSH
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          
          # Configurar el archivo known_hosts para evitar advertencias de seguridad
          mkdir -p ~/.ssh
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

          # Verificar la conexión SSH
          echo "Attempting SSH connection..."
          if ssh -i /tmp/id_rsa -o ConnectTimeout=10 -o LogLevel=DEBUG $VPS_USER@$VPS_HOST 'echo "SSH connection successful"'; then
            echo "SSH connection successful"
          else
            echo "Failed to connect via SSH" >&2
            exit 1
          fi

          # Subir la imagen Docker al VPS
          echo "Uploading Docker image..."
          docker save myapp:latest | bzip2 | ssh -i /tmp/id_rsa $VPS_USER@$VPS_HOST 'bunzip2 | docker load'
          
          # Desplegar la aplicación usando Docker Compose
          echo "Deploying Docker Compose..."
          ssh -i /tmp/id_rsa $VPS_USER@$VPS_HOST 'docker-compose -f /home/files-docker-compose/docker-compose.yml up -d --build'

          # Limpiar el archivo temporal de la clave SSH
          rm /tmp/id_rsa
